// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCExwxnUYJYqr-KpsGebK41HGqZLN-U4FY',
    appId: '1:312270422586:web:5c79a88ce3edecb6a8eb03',
    messagingSenderId: '312270422586',
    projectId: 'bartek-hub-55399',
    authDomain: 'bartek-hub-55399.firebaseapp.com',
    storageBucket: 'bartek-hub-55399.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCUvjRGQDbrJ4y9WTrvVsW-bnVzrISKgQ',
    appId: '1:312270422586:android:741e45ed730664f7a8eb03',
    messagingSenderId: '312270422586',
    projectId: 'bartek-hub-55399',
    storageBucket: 'bartek-hub-55399.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaJqHVK5U6g4D5RHbYJZXTxeZzM037jSA',
    appId: '1:312270422586:ios:eeb5e9ef42ea0b89a8eb03',
    messagingSenderId: '312270422586',
    projectId: 'bartek-hub-55399',
    storageBucket: 'bartek-hub-55399.appspot.com',
    iosClientId: '312270422586-jin5ofuecsb1qc2jmocbpp8fga9ir4bf.apps.googleusercontent.com',
    iosBundleId: 'com.example.bartekhub',
  );
}
