// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAetzBtZ9KE0xAFlgaWF2_9U9EKeSTZ0Os',
    appId: '1:926999703172:web:4ea5eb75da645328d89cd1',
    messagingSenderId: '926999703172',
    projectId: 'dailytube-74a00',
    authDomain: 'dailytube-74a00.firebaseapp.com',
    storageBucket: 'dailytube-74a00.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2IRYMqCfknsFtsZQK_isDgoMtH6glQhQ',
    appId: '1:926999703172:android:8a46f430b314f313d89cd1',
    messagingSenderId: '926999703172',
    projectId: 'dailytube-74a00',
    storageBucket: 'dailytube-74a00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_3rv3N5l0BJ7xerzWaNta9JXrCkIC7KQ',
    appId: '1:926999703172:ios:c63964c6bcb8bdbbd89cd1',
    messagingSenderId: '926999703172',
    projectId: 'dailytube-74a00',
    storageBucket: 'dailytube-74a00.appspot.com',
    iosClientId: '926999703172-7ohudkjg32np9brg5m6710mb1urjbfcf.apps.googleusercontent.com',
    iosBundleId: 'com.example.dailytube',
  );
}
