// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxFkv45sexrPYXCCAdbTlVXuiRbu6dwk0',
    appId: '1:1002402080581:web:f519493900588607f0c02c',
    messagingSenderId: '1002402080581',
    projectId: 'bartek-hub',
    authDomain: 'bartek-hub.firebaseapp.com',
    storageBucket: 'bartek-hub.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTwCP1deovuiDR08ht0l4jF05he3g1WJU',
    appId: '1:1002402080581:android:264b1473fa4f7ebbf0c02c',
    messagingSenderId: '1002402080581',
    projectId: 'bartek-hub',
    storageBucket: 'bartek-hub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYNaD1hNB94VkTY7aSg3Eh9CTeFORy398',
    appId: '1:1002402080581:ios:96c14f721821fd4ff0c02c',
    messagingSenderId: '1002402080581',
    projectId: 'bartek-hub',
    storageBucket: 'bartek-hub.appspot.com',
    iosClientId: '1002402080581-qumq4kbdpi15583724h9phs4cfjk62b7.apps.googleusercontent.com',
    iosBundleId: 'io.flutter.flutter.app',
  );
}
